export const SET_COMPARE_SELECT1 = "SET_COMPARE_SELECT1";
export const SET_COMPARE_SELECT2 = "SET_COMPARE_SELECT2";
export const SET_SHOW_DETAILS = "SET_SHOW_DETAILS";
export const SET_BTSDATA1 = "SET_BTSDATA1";
export const SET_BTSDATA2 = "SET_BTSDATA2";
