let datatabel = [
  {
    id: "1",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "ASSIGNED",
  },
  {
    id: "2",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
  {
    id: "3",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
  {
    id: "4",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "ASSIGNED",
  },
  {
    id: "5",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
  {
    id: "6",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "ASSIGNED",
  },
  {
    id: "7",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
  {
    id: "8",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
  {
    id: "9",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
  {
    id: "10",
    kode: "DFR024513",
    instansi: "PT. ADYAWINSA",
    lokasi: "PUUWIWIRANO",
    tanggal: "01/08/2021",
    status: "REVIEWED",
  },
];

export { datatabel };
