let datatabel = [
  {
    id: "1",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "2",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "3",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "4",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "5",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "6",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "7",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "8",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "9",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
  {
    id: "10",
    provinsi: "DKI Jakarta",
    kabupaten: "Jakarta Selatan",
    kecamatan: "Cilandak Timur",
    desa: "Kemang Selatan",
    longitude: "11.2401° E",
    latitude: "12.457° S",
  },
];

export { datatabel };
