let datatabel = [
  {
    id: "1",
    nama: "AAA",
    username: "aaa12",
    tipe: "Admin Surveyor",
    email: "aaa@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "2",
    nama: "BBB",
    username: "bbb12",
    tipe: "Admin Surveyor",
    email: "bbb@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "3",
    nama: "CCC",
    username: "ccc12",
    tipe: "Admin Surveyor",
    email: "ccc@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "4",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "5",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "6",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "7",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "8",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "9",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
  {
    id: "10",
    nama: "DDD",
    username: "ddd12",
    tipe: "Admin Surveyor",
    email: "ddd@mail.com",
    instansi: "PT ABCDE",
    telepon: "08123456789",
    linkdoc: "https://www.google.com/",
  },
];

export { datatabel };
